import * as CircleCI from '../src/index';
import * as YAML from 'yaml';
import { version as SDKVersion } from '../src/package-version.json';

describe('Generate a Setup workflow config', () => {
  const myConfig = new CircleCI.config.Config(true).stringify();
  it('Should produce a blank config with Setup set to true', () => {
    const expected = {
      version: 2.1,
      setup: true,
      jobs: {},
      workflows: {},
    };
    expect(YAML.parse(myConfig)).toEqual(expected);
  });
  it('Should include the version comment string', () => {
    const comment = `# This configuration has been automatically generated by the CircleCI Config SDK.
# For more information, see https://github.com/CircleCI-Public/circleci-config-sdk-ts
# SDK Version: ${SDKVersion}
`;
    expect(myConfig).toContain(comment);
  });
});

describe('Generate a config with parameters', () => {
  const myConfig = new CircleCI.config.Config(true);

  myConfig.defineParameter('greeting', 'string', 'hello world');

  const configResult = myConfig.stringify();

  it('Should produce a blank config with parameters', () => {
    const expected = {
      version: 2.1,
      setup: true,
      parameters: {
        greeting: {
          type: 'string',
          default: 'hello world',
        },
      },
      jobs: {},
      workflows: {},
    };
    expect(YAML.parse(configResult)).toEqual(expected);
  });
  it('Should include the version comment string', () => {
    const comment = `# This configuration has been automatically generated by the CircleCI Config SDK.
# For more information, see https://github.com/CircleCI-Public/circleci-config-sdk-ts
# SDK Version: ${SDKVersion}
`;
    expect(configResult).toContain(comment);
  });
});

describe('Parse a fully complete config', () => {
  const myConfig = new CircleCI.config.Config();

  myConfig.defineParameter('greeting', 'string', 'hello world!');

  const docker = new CircleCI.executor.DockerExecutor('cimg/node:lts');
  const reusableDocker = new CircleCI.executor.ReusableExecutor(
    'docker',
    docker,
  );

  myConfig.addReusableExecutor(reusableDocker);

  const customCommand = new CircleCI.commands.reusable.CustomCommand(
    'say_hello',
    [
      new CircleCI.commands.Run({
        command: 'echo << parameters.greeting >>',
      }),
    ],
    new CircleCI.parameters.CustomParametersList([
      new CircleCI.parameters.CustomParameter('greeting', 'string'),
    ]),
  );

  myConfig.addCustomCommand(customCommand);

  const jobA = new CircleCI.job.Job('my-job-A', reusableDocker, [
    new CircleCI.commands.reusable.ReusableCommand(customCommand, {
      greeting: '<< pipeline.parameters.greeting >>',
    }),
  ]);
  const jobB = new CircleCI.job.Job('my-job-B', reusableDocker, [
    new CircleCI.commands.reusable.ReusableCommand(customCommand, {
      greeting: 'sup world!',
    }),
  ]);

  myConfig.addJob(jobA);
  myConfig.addJob(jobB);

  const myWorkflow = new CircleCI.workflow.Workflow('my-workflow');

  myWorkflow.addJob(jobA);
  myWorkflow.addJob(jobB, { requires: [jobA.name] });

  myConfig.addWorkflow(myWorkflow);

  const configResult = {
    version: 2.1,
    setup: false,
    commands: {
      say_hello: {
        parameters: {
          greeting: {
            type: 'string',
          },
        },
        steps: [
          {
            run: {
              command: 'echo << parameters.greeting >>',
            },
          },
        ],
      },
    },
    parameters: {
      greeting: {
        type: 'string',
        default: 'hello world!',
      },
    },
    executors: {
      docker: {
        docker: [{ image: 'cimg/node:lts' }],
      },
    },
    jobs: {
      'my-job-A': {
        executor: 'docker',
        steps: [
          {
            say_hello: {
              greeting: '<< pipeline.parameters.greeting >>',
            },
          },
        ],
      },
      'my-job-B': {
        executor: 'docker',
        steps: [
          {
            say_hello: {
              greeting: 'sup world!',
            },
          },
        ],
      },
    },
    workflows: {
      'my-workflow': {
        jobs: [{ 'my-job-A': {} }, { 'my-job-B': { requires: ['my-job-A'] } }],
      },
    },
  };

  it('Should produce a blank config with parameters', () => {
    expect(CircleCI.config.parseConfig(configResult)).toEqual(myConfig);
  });

  it('Should be fully circular', () => {
    expect(
      CircleCI.config.parseConfig(YAML.parse(myConfig.stringify())),
    ).toEqual(myConfig);
  });
});
