import * as CircleCI from '../src/index';
import * as YAML from 'yaml';
import { version as SDKVersion } from '../src/package-version.json';

describe('Generate a Setup workflow config', () => {
  const myConfig = new CircleCI.Config(true);
  const docker = new CircleCI.Executor.DockerExecutor('cimg/node:lts');
  const helloWorld = new CircleCI.Command.Run({
    command: 'echo hello world',
  });
  const job = new CircleCI.Job('my-job', docker, [helloWorld]);
  myConfig.addJob(job);
  const configYAML = myConfig.stringify();
  it('Should produce a config with one job, and Setup set to true', () => {
    const expected = {
      version: 2.1,
      setup: true,
      jobs: {
        'my-job': {
          docker: [
            {
              image: 'cimg/node:lts',
            },
          ],
          resource_class: 'medium',
          steps: [
            {
              run: {
                command: 'echo hello world',
              },
            },
          ],
        },
      },
      workflows: {},
    };
    expect(YAML.parse(configYAML)).toEqual(expected);
  });
  it('Should include the version comment string', () => {
    const comment = `# This configuration has been automatically generated by the CircleCI Config SDK.
# For more information, see https://github.com/CircleCI-Public/circleci-config-sdk-ts
# SDK Version: ${SDKVersion}
`;
    expect(configYAML).toContain(comment);
  });
});
