import { Scalar, stringify } from 'yaml';
import { version as SDKVersion } from '../../package-version.json';
import { Generable } from '../Components';
import { CustomCommandShape } from '../Components/Commands/types/Command.types';
import { ReusableExecutor } from '../Components/Executors/exports/ReusableExecutor';
import { ReusableExecutorShape } from '../Components/Executors/types/ReusableExecutor.types';
import { Job } from '../Components/Job';
import { JobsShape } from '../Components/Job/types/Job.types';
import { CustomParametersList } from '../Components/Parameters';
import { Parameterized } from '../Components/Parameters/exports/Parameterized';
import { PipelineParameterLiteral } from '../Components/Parameters/types/CustomParameterLiterals.types';
import { CustomCommand } from '../Components/Reusable';
import { Workflow } from '../Components/Workflow';
import { WorkflowsShape } from '../Components/Workflow/types/Workflow.types';
import { OrbImportsShape } from '../Orb/types/Orb.types';
import { CommonConfig } from './exports/CommonConfig';
import { GenerableType } from './exports/Mapping';
import { Validator } from './exports/Validator';
import { Pipeline } from './Pipeline';
import {
  CircleCIConfigObject,
  CircleCIConfigShape,
  ConfigVersion,
} from './types';

/**
 * A CircleCI configuration. Instantiate a new config and add CircleCI config elements.
 */
export class Config
  extends CommonConfig
  implements CircleCIConfigObject, Parameterized<PipelineParameterLiteral>
{
  /**
   * The version field is intended to be used in order to issue warnings for deprecation or breaking changes.
   */
  version: ConfigVersion = 2.1;
  /**
   * A Workflow is comprised of one or more uniquely named jobs.
   */
  workflows: Workflow[] = [];
  /**
   * A parameter allows custom data to be passed to a pipeline.
   */
  parameters?: CustomParametersList<PipelineParameterLiteral>;
  /**
   * Access information about the current pipeline.
   */
  pipeline: Pipeline = new Pipeline();
  /**
   * Designates the config.yaml for use of CircleCI’s dynamic configuration feature.
   */
  setup: boolean;

  /**
   * Instantiate a new CircleCI config. Build up your config by adding components.
   * @param jobs - Instantiate with pre-defined Jobs.
   * @param workflows - Instantiate with pre-defined Workflows.
   * @param commands - Instantiate with pre-defined reusable Commands.
   */
  constructor(
    setup = false,
    jobs: Job[] = [],
    workflows?: Workflow[],
    executors?: ReusableExecutor[],
    commands?: CustomCommand[],
    parameters?: CustomParametersList<PipelineParameterLiteral>,
  ) {
    super(jobs, executors, commands);
    this.setup = setup;
    this.workflows = workflows || [];
    this.parameters = parameters;
  }

  /**
   * Add a Workflow to the current Config. Chainable
   * @param workflow - Injectable Workflow
   */
  addWorkflow(workflow: Workflow): this {
    this.workflows.push(workflow);
    return this;
  }

  /**
   * Define a pipeline parameter for the current Config. Chainable
   *
   * @param name - The name of the parameter
   * @param type - The type of parameter
   * @param defaultValue - The default value of the parameter
   * @param description - A description of the parameter
   * @param enumValues - An array of possible values for parameters of enum type
   */
  defineParameter(
    name: string,
    type: PipelineParameterLiteral,
    defaultValue?: unknown,
    description?: string,
    enumValues?: string[],
  ): Config {
    if (!this.parameters) {
      this.parameters = new CustomParametersList<PipelineParameterLiteral>();
    }

    this.parameters.define(name, type, defaultValue, description, enumValues);

    return this;
  }

  private prependVersionComment(source: string): string {
    const comment = `# This configuration has been automatically generated by the CircleCI Config SDK.
# For more information, see https://github.com/CircleCI-Public/circleci-config-sdk-ts
# SDK Version: ${SDKVersion}
`;
    return `${comment}\n${source}`;
  }

  /**
   * Export the CircleCI configuration as a YAML string.
   */
  generate(): string {
    const generatedWorkflows = generateList<WorkflowsShape>(this.workflows, {});
    const generatedJobs = generateList<JobsShape>(this.jobs, {});
    const generatedExecutors = generateList<ReusableExecutorShape>(
      this.executors,
    );
    const generatedCommands = generateList<CustomCommandShape>(this.commands);
    const generatedOrbs = generateList<OrbImportsShape>(this.orbs);
    const generatedParameters = this.parameters?.generate();

    const generatedConfig: CircleCIConfigShape = {
      version: this.version,
      setup: this.setup,
      parameters: generatedParameters,
      commands: generatedCommands,
      executors: generatedExecutors,
      jobs: generatedJobs,
      workflows: generatedWorkflows,
      orbs: generatedOrbs,
    };

    // remove undefined values
    Object.entries(generatedConfig).forEach(([key, value]) => {
      if (value === undefined) {
        delete generatedConfig[key as keyof CircleCIConfigShape];
      }
    });

    return this.prependVersionComment(
      stringify(generatedConfig as CircleCIConfigShape, {
        defaultStringType: Scalar.PLAIN,
        lineWidth: 0,
        minContentWidth: 0,
        doubleQuotedMinMultiLineLength: 999,
      }),
    );
  }

  get generableType(): GenerableType {
    return GenerableType.CONFIG;
  }
}

function generateList<Shape>(listIn?: Generable[], failSafe?: Shape): Shape {
  if (!listIn) {
    return failSafe as Shape;
  }

  return Object.assign(
    {},
    ...listIn.map((generable) => {
      return generable.generate();
    }),
  );
}

export { Validator };
